# Generated by Django 5.1.3 on 2024-12-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_keypair_encodedimage_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encodedimage',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
